### ISSUE TITLE
psf_reduce incorrectly calls the frame processor

### ISSUE THREAD

**Issue by wildjames** [HiPERCAM/hipercam#93]
hipercam version 1.1.5. 

Calling psf_reduce results in the following error:

```
$ psf_reduce
rfile - reduce file [run013_psf]: 
run - run name [2016_08_21/run013]: 
first - first frame to reduce [1]: 2
log - name of log file to store results [run013_psf]: 
tkeep - number of minute of data to keep in internal buffers (0 for all) [0.0]: 
lplot - do you want to plot light curves? [True]: 
implot - do you want to plot images? [True]: 
ccd - CCD(s) to plot [0 for all] [0]: 
nx - number of panels in X [3]: 
msub - subtract median from each window? [True]: 
iset - set intensity a(utomatically), d(irectly) or with p(ercentiles)? [p]: 
plo - lower intensity limit percentile [0.5]: 
phi - upper intensity limit percentile [95.0]: 
xlo - left-hand X value [0.0]: 
xhi - right-hand X value [1000.0]: 
ylo - lower Y value [0.0]: 
yhi - upper Y value [1000.0]: 
Frame 2: 2016-08-21T23:47:34.789542337 [NOK]Traceback (most recent call last):
  File "/usr/local/bin/psf_reduce", line 8, in <module>
    sys.exit(psf_reduce())
  File "/usr/local/lib/python3.7/dist-packages/hipercam/scripts/psf_reduce.py", line 559, in psf_reduce
    results = processor(pccds, mccds, nframes)
TypeError: __call__() missing 1 required positional argument: 'nframes'
```

**Comment by wildjames** [comment]
After a quick look, it seems the processor call expects `(pccds, bccds, mccds, nframes)`, but the call fails to provide `bccds`. I'll see if I can fix this.

**Comment by wildjames** [comment]
I've massaged the psf_reduce code to run without complaining, however I find the same issue with errors not being correctly handled (or at least, I very much hope they aren't) as in PR #80. Here's a comparison between an optimal and psf reduction:

![optimal_vs_psf](https://user-images.githubusercontent.com/34480320/136020552-9dbc9b6b-67d3-4026-ac98-ffedf38b57b2.png)

My code is currently on my own branch, [here](https://github.com/wildjames/hipercam/tree/psf_update).

**Comment by trmrsh** [comment]
Hi James, thanks a lot for taking this on! I knew that psf_reduce would be broken after many changes to reduce over the past year, as they do share some common code which changed. The easiest way to end up with the wrong uncertainties after the Lev-marq fit I think would be if the input uncertainties were somehow wrong. Is that possible? I don't know the psf_reduce code at all, but the code snippet _get_uncertainties looks plausible to me.

The other issue you point out is a difference in the mean levels. It might be good to compare with a normal extraction rather than an optimal one. Also, if this is a crowded field (?) then there could be differences, although I am not sure I would expect those to make the PSF value higher.

**Comment by wildjames** [comment]
Yeah, I think a faint target was the culprit there. Here's the same field as star A from before, but I targeted some brighter stars. Here's the lightcurves:

![optimal_normal_psf](https://user-images.githubusercontent.com/34480320/136190094-032aa63e-c868-4ef7-b5f5-66c0731bfe36.png)

The normal reduction is systematically higher because of contamination from a nearby star, so that's expected.
